version: '2'
services:
  mailcatcher:
    image: odaniait/mailcatcher-docker:latest
    ports:
      - "2525:2525"
      - "1080:1080"
  consul:
    image: odaniait/docker-consul:latest
    environment:
      BOOTSTRAP_NODE: "true"
    tty: true
    stdin_open: true
  redis:
    image: redis:alpine
    tty: true
    stdin_open: true
  mongo:
    image: mongo
    tty: true
    stdin_open: true
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch:2.3
    tty: true
    stdin_open: true
    ports:
      - "9200:9200"
      - "9300:9300"
