version: '2'
services:
  odaniastatic:
    build: git/odania-static
    ports:
      - "8081:80"
    links:
      - consul
    volumes:
      - ./fixtures/static:/srv/static
    tty: true
    stdin_open: true
  varnish:
    build: git/odania-varnish
    ports:
      - "8080:80"
    links:
      - mailcatcher
      - consul
    environment:
      ENVIRONMENT: development
    tty: true
    stdin_open: true
  core:
    build: git/odania-core
    ports:
      - "9292:9292"
      - "8082:80"
    links:
      - mailcatcher
      - consul
    depends_on:
      - odaniastatic
    volumes:
      - ./fixtures/static/data:/srv/static
      - ./fixtures/static/config:/srv/config
    environment:
      ENVIRONMENT: development
    tty: true
    stdin_open: true
  mailcatcher:
    extends:
      file: docker-compose.d/base.yml
      service: mailcatcher
  consul:
    extends:
      file: docker-compose.d/base.yml
      service: consul
