version: '2'
services:
  odaniastatic:
    build: git/odania-static
    ports:
      - "8081:80"
    links:
      - consul
    environment:
      - CONSUL_ADDR=http://consul:8500
    volumes:
      - ./fixtures/static:/srv/static
      - ./git/odania-static:/srv/odania
    tty: true
    stdin_open: true
  varnish:
    build: git/odania-varnish
    ports:
      - "8080:80"
    links:
      - mailcatcher
      - consul
    environment:
      ENVIRONMENT: development
    volumes:
      - ./git/odania-varnish:/srv/odania
    tty: true
    stdin_open: true
  core:
    build: git/odania-core
    ports:
      - "9292:9292"
      - "8082:80"
    links:
      - mailcatcher
      - consul
    environment:
      - CONSUL_ADDR=http://consul:8500
      - ENVIRONMENT=development
    volumes:
      - ./fixtures/core/config:/srv/config
      - ./git/odania-core:/srv/odania
    tty: true
    stdin_open: true
  mailcatcher:
    extends:
      file: docker-compose.d/base.yml
      service: mailcatcher
  consul:
    extends:
      file: docker-compose.d/base.yml
      service: consul
  redis:
    extends:
      file: docker-compose.d/base.yml
      service: redis
  mongo:
    extends:
      file: docker-compose.d/base.yml
      service: mongo
  elasticsearch:
    extends:
      file: docker-compose.d/base.yml
      service: elasticsearch
